substitutions:
    device: "strom-pris-ur"
    name: Strøm-Pris Ur
    ssid: "strom-pris-Ur"

dashboard_import:
  package_import_url: github://briis/strom-pris-ur-esphome/strom-pris-ur.yaml@main
  import_full_config: false # or true

packages:
  device_base: !include common/strom-pris-ur-base.yaml
  functions: !include common/strom-pris-ur.h
