substitutions:
    device: "strom-pris-ur"
    name: Strøm-Pris Ur
    ssid: "strom-pris-Ur"

esphome:
  name: "${device}"
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: "briis.${device}"
    version: "1.0.0"

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://briis/strom-pris-ur-esphome/strom-pris-ur.yaml@main
  import_full_config: false # or true

wifi:
  # Set up a wifi access point
  ap: {}
    

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none